// Command avangard-server runs an AVANGARD tunnel server.
//
// Subcommands:
//   - keygen   — generate a fresh Noise X25519 server-static keypair and
//     a UUID, print the matching avangard:// URI for the client.
//   - run      — read a YAML config, listen on QUIC and/or TCP, serve.
//   - selfcert — issue a self-signed cert (dev only).
package main

import (
	"context"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/base64"
	"encoding/pem"
	"fmt"
	"log/slog"
	"math/big"
	mrand "math/rand"
	"net"
	"os"
	"os/signal"
	"path/filepath"
	"syscall"
	"time"

	"github.com/avangard/avangard/pkg/auth"
	"github.com/avangard/avangard/pkg/config"
	"github.com/avangard/avangard/pkg/transport"
	quictransport "github.com/avangard/avangard/pkg/transport/quic"
	tcptransport "github.com/avangard/avangard/pkg/transport/tcp"
	"github.com/avangard/avangard/pkg/tunnel"
	"github.com/avangard/avangard/pkg/uri"
	"github.com/spf13/cobra"
)

func main() {
	root := &cobra.Command{
		Use:   "avangard-server",
		Short: "AVANGARD tunnel server",
	}
	root.AddCommand(newKeygenCmd(), newRunCmd(), newSelfCertCmd())
	if err := root.Execute(); err != nil {
		os.Exit(1)
	}
}

func newKeygenCmd() *cobra.Command {
	var host, decoy, outDir string
	var port int
	cmd := &cobra.Command{
		Use:   "keygen",
		Short: "Generate server keys + URI",
		RunE: func(cmd *cobra.Command, args []string) error {
			static, err := auth.GenerateStatic()
			if err != nil {
				return err
			}
			uid := genUUID()
			cfg := &uri.Config{
				UUID:      uid,
				Host:      host,
				Port:      port,
				SNI:       decoy,
				Mode:      uri.ModeAuto,
				Region:    "auto",
				ServerPub: static.Public,
				Name:      "avangard",
			}
			if outDir != "" {
				if err := os.MkdirAll(outDir, 0o700); err != nil {
					return err
				}
				priv := base64.RawStdEncoding.EncodeToString(static.Private)
				body := fmt.Sprintf(`# Auto-generated by avangard-server keygen
listen:
  quic: ":%d"
  tcp: ":%d"
decoy:
  domain: %s
  addr: %s:443
tls:
  cert_file: %s/cert.pem
  key_file: %s/key.pem
auth:
  static_privkey_b64: %q
  accepted_uuids:
    - %q
logging:
  level: info
`, port, port, decoy, decoy, outDir, outDir, priv, uid)
				if err := os.WriteFile(filepath.Join(outDir, "server.yaml"), []byte(body), 0o600); err != nil {
					return err
				}
				fmt.Printf("server config written to %s/server.yaml\n", outDir)
			}
			fmt.Println("--- AVANGARD URI ---")
			fmt.Println(cfg.String())
			fmt.Println("--- Server static pubkey (b64) ---")
			fmt.Println(base64.RawStdEncoding.EncodeToString(static.Public))
			return nil
		},
	}
	cmd.Flags().StringVar(&host, "host", "127.0.0.1", "public host")
	cmd.Flags().IntVar(&port, "port", 443, "public port")
	cmd.Flags().StringVar(&decoy, "decoy", "www.yandex.ru", "decoy domain (SNI)")
	cmd.Flags().StringVar(&outDir, "out", "", "if set, write config + dirs here")
	return cmd
}

func newSelfCertCmd() *cobra.Command {
	var dir, host string
	cmd := &cobra.Command{
		Use:   "selfcert",
		Short: "Issue a self-signed certificate (dev only)",
		RunE: func(cmd *cobra.Command, args []string) error {
			priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
			if err != nil {
				return err
			}
			tmpl := &x509.Certificate{
				SerialNumber: big.NewInt(time.Now().UnixNano()),
				Subject:      pkix.Name{CommonName: host},
				NotBefore:    time.Now().Add(-time.Hour),
				NotAfter:     time.Now().Add(365 * 24 * time.Hour),
				KeyUsage:     x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment,
				ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
				DNSNames:     []string{host, "localhost"},
				IPAddresses:  []net.IP{net.ParseIP("127.0.0.1"), net.ParseIP("::1")},
			}
			der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &priv.PublicKey, priv)
			if err != nil {
				return err
			}
			keyDER, _ := x509.MarshalECPrivateKey(priv)
			if err := os.MkdirAll(dir, 0o700); err != nil {
				return err
			}
			cb := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der})
			kb := pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: keyDER})
			if err := os.WriteFile(filepath.Join(dir, "cert.pem"), cb, 0o600); err != nil {
				return err
			}
			if err := os.WriteFile(filepath.Join(dir, "key.pem"), kb, 0o600); err != nil {
				return err
			}
			fmt.Printf("wrote %s/cert.pem and %s/key.pem (CN=%s)\n", dir, dir, host)
			return nil
		},
	}
	cmd.Flags().StringVar(&dir, "out", "/etc/avangard", "directory")
	cmd.Flags().StringVar(&host, "host", "localhost", "common name")
	return cmd
}

func newRunCmd() *cobra.Command {
	var configPath string
	cmd := &cobra.Command{
		Use:   "run",
		Short: "Run the server",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.LoadServer(configPath)
			if err != nil {
				return err
			}
			lvl := slog.LevelInfo
			if cfg.Logging.Level == "debug" {
				lvl = slog.LevelDebug
			}
			logger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: lvl}))

			cert, err := tls.LoadX509KeyPair(cfg.TLS.CertFile, cfg.TLS.KeyFile)
			if err != nil {
				return fmt.Errorf("load TLS: %w", err)
			}

			privBytes, err := base64.RawStdEncoding.DecodeString(cfg.Auth.StaticPrivKeyB64)
			if err != nil {
				return fmt.Errorf("priv b64: %w", err)
			}
			static, err := auth.StaticFromPriv(privBytes)
			if err != nil {
				return fmt.Errorf("static key: %w", err)
			}

			srvCfg := transport.ServerConfig{
				AcceptedUUIDs: cfg.Auth.AcceptedUUIDs,
				NoiseStatic:   static,
				TLSCert:       cert,
				DecoyAddr:     cfg.Decoy.Addr,
				Logger:        logger,
			}

			var listeners []transport.Listener
			if cfg.Listen.QUIC != "" {
				qcfg := srvCfg
				qcfg.Addr = cfg.Listen.QUIC
				ln, err := quictransport.Listen(qcfg)
				if err != nil {
					return fmt.Errorf("quic listen: %w", err)
				}
				logger.Info("quic listening", "addr", ln.Addr())
				listeners = append(listeners, ln)
			}
			if cfg.Listen.TCP != "" {
				tcpcfg := srvCfg
				tcpcfg.Addr = cfg.Listen.TCP
				var magic []string
				if cfg.Decoy.Domain != "" {
					magic = []string{cfg.Decoy.Domain}
				}
				ln, err := tcptransport.Listen(tcpcfg, magic)
				if err != nil {
					return fmt.Errorf("tcp listen: %w", err)
				}
				logger.Info("tcp listening", "addr", ln.Addr())
				listeners = append(listeners, ln)
			}
			if len(listeners) == 0 {
				return fmt.Errorf("no listeners configured")
			}
			composite := tunnel.NewComposite(listeners...)
			srv := tunnel.NewServer(composite, cfg.Auth.AcceptedUUIDs, logger)

			ctx, cancel := context.WithCancel(context.Background())
			defer cancel()
			go func() {
				ch := make(chan os.Signal, 1)
				signal.Notify(ch, os.Interrupt, syscall.SIGTERM)
				<-ch
				logger.Info("shutting down")
				cancel()
				_ = srv.Close()
			}()
			return srv.Serve(ctx)
		},
	}
	cmd.Flags().StringVar(&configPath, "config", "/etc/avangard/server.yaml", "config file")
	return cmd
}

func genUUID() string {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		// Fallback to non-crypto rand to avoid hard failure on weird envs.
		mrand.Read(b[:])
	}
	b[6] = (b[6] & 0x0f) | 0x40 // v4
	b[8] = (b[8] & 0x3f) | 0x80
	return fmt.Sprintf("%08x-%04x-%04x-%04x-%012x",
		b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}
